spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ENC(0BhualGW0BB2+o01X91JU/3o9uvy0rx0ahRoe7Nx5T9YnE608Leu/z+PqHFUAi6A5SJEafP9ftSxgyFRV14qJp+PHstvVxqaSNHouMmDE7EjiG31eUFV0g==)
    username: ENC(ocSzxctREzIETjgwXhE9AxBwjNPsR3NH)
    password: ENC(nXhGXszoymgwduOXrMSPG6g77ec429Mv)

mybatis:
  type-aliases-package: site.match5.domain.* # 파라미터나,리턴타입(resultType)에 대한 정보를 적을때 해당 타입의 패키지이름까지 적어줘야하는데 미리 패키지를 설정해주면 생략가능하다.
  configuration:
    map-underscore-to-camel-case: true  # 데이터베이스는 대부분 언더스코어(_)를 사용하는데 그것을 객체필드가 주로쓰는 카멜케이스로 변환해주는 설정
  mapper-locations: classpath:mapper/**/*.xml # xml 은 resources 아래 mapper 인터페이스와 같은 이름의 경로에 존재해야하지만 해당 설정으로 원하는곳에 보관 가능하다.
