--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."CLIENT" 
   (	"ID" NUMBER(*,0), 
	"LEVEL_ID" NUMBER(*,0), 
	"GENDER" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" NUMBER(*,0), 
	"NICKNAME" NVARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"KAKAO_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_EXP" NUMBER DEFAULT 0, 
	"CHARGE_AMOUNT" NUMBER DEFAULT 0, 
	"POINT" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IMAGE_URL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MATCH_COUNT" NUMBER DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."LEVEL_ID" IS '레벨';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."GENDER" IS '성별';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."AGE" IS '나이';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."KAKAO_ID" IS '카카오고유번호';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."CURRENT_EXP" IS '현재 경험치';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."CHARGE_AMOUNT" IS '충전금액';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."POINT" IS '포인트';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."CREATED_AT" IS '생성시각';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."UPDATED_AT" IS '수정시각';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."IMAGE_URL" IS '프로필 이미지';
   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT"."MATCH_COUNT" IS '진행한경기수';
   COMMENT ON TABLE "MATCH5_DBA"."CLIENT"  IS '유저';
  GRANT DELETE ON "MATCH5_DBA"."CLIENT" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."CLIENT" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."CLIENT" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."CLIENT" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_CLIENT" ON "MATCH5_DBA"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018484
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."SYS_C0018484" ON "MATCH5_DBA"."CLIENT" ("NICKNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0018485
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."SYS_C0018485" ON "MATCH5_DBA"."CLIENT" ("KAKAO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger CLIENT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."CLIENT_ID_TRIGGER" BEFORE
    INSERT ON client
    FOR EACH ROW
BEGIN
    SELECT
        client_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."CLIENT_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_CLIENT_LEVEL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."UPDATE_CLIENT_LEVEL" 
    BEFORE UPDATE OF current_exp ON client
    FOR EACH ROW
DECLARE
    new_level_id FUTSAL_LEVEL.id%TYPE;
BEGIN
    SELECT id INTO new_level_id
    FROM (
             SELECT l.id
             FROM FUTSAL_LEVEL l
             WHERE   l.req_exp >= :NEW.current_exp
             ORDER BY l.req_exp
         )
    WHERE ROWNUM = 1;

    IF new_level_id IS NOT NULL THEN
        :NEW.level_id := new_level_id;
    END IF;
END;
/
ALTER TRIGGER "MATCH5_DBA"."UPDATE_CLIENT_LEVEL" ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT" MODIFY ("LEVEL_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_CLIENT"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD CONSTRAINT "AGE_CHECK" CHECK (age >= 20 and age <= 49) ENABLE;
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD CONSTRAINT "NICKNAME_LENGTH_CHECK" CHECK (LENGTH(nickname) BETWEEN 2 AND 15) ENABLE;
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD UNIQUE ("KAKAO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD CONSTRAINT "CHECK_GENDER" CHECK (gender IN ('M', 'F')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."CLIENT" ADD CONSTRAINT "FK_FUTSAL_LEVEL_TO_CLIENT" FOREIGN KEY ("LEVEL_ID")
	  REFERENCES "MATCH5_DBA"."FUTSAL_LEVEL" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for Table CLIENT_MATCHING_STATUS
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."CLIENT_MATCHING_STATUS" 
   (	"USER_ID" NUMBER, 
	"STATUS" NUMBER DEFAULT 0, 
	"MATCH_DAY" TIMESTAMP (6), 
	"MATCH_TIME" NUMBER DEFAULT NULL
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."CLIENT_MATCHING_STATUS"."STATUS" IS '0=매칭전,1=매칭대기중,2=매칭확정누름,3=매칭완료';
--------------------------------------------------------
--  DDL for Index CLIENT_MATCHING_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."CLIENT_MATCHING_STATUS_PK" ON "MATCH5_DBA"."CLIENT_MATCHING_STATUS" ("USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table CLIENT_MATCHING_STATUS
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."CLIENT_MATCHING_STATUS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."CLIENT_MATCHING_STATUS" ADD CONSTRAINT "CLIENT_MATCHING_STATUS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT_MATCHING_STATUS
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."CLIENT_MATCHING_STATUS" ADD CONSTRAINT "CLIENT_MATCHING_STATUS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table COURT
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."COURT" 
   (	"ID" NUMBER(*,0), 
	"STADIUM_ID" NUMBER(*,0), 
	"AVG_RATE" NUMBER DEFAULT 0, 
	"IS_OUTDOOR" NUMBER(*,0), 
	"SIZE_X" NUMBER(*,0), 
	"SIZE_Y" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."ID" IS '구장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."STADIUM_ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."AVG_RATE" IS '평균평점';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."IS_OUTDOOR" IS '실내외유무 실내=0,실외=1';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."SIZE_X" IS '가로크기';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT"."SIZE_Y" IS '세로크기';
--------------------------------------------------------
--  DDL for Index COURT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."COURT_PK" ON "MATCH5_DBA"."COURT" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger COURT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."COURT_ID_TRIGGER" BEFORE
    INSERT ON court
    FOR EACH ROW
BEGIN
    SELECT
        court_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."COURT_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT" MODIFY ("STADIUM_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT" MODIFY ("IS_OUTDOOR" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT" ADD CONSTRAINT "COURT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT" ADD CONSTRAINT "COURT_FK1" FOREIGN KEY ("STADIUM_ID")
	  REFERENCES "MATCH5_DBA"."STADIUM" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table COURT_IMAGE
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."COURT_IMAGE" 
   (	"ID" NUMBER(*,0), 
	"IMAGE_URL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"COURT_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."COURT_IMAGE"."ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_IMAGE"."IMAGE_URL" IS '이미지url';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_IMAGE"."COURT_ID" IS '구장아이디';
   COMMENT ON TABLE "MATCH5_DBA"."COURT_IMAGE"  IS '풀살장 이미지';
  GRANT DELETE ON "MATCH5_DBA"."COURT_IMAGE" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."COURT_IMAGE" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."COURT_IMAGE" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."COURT_IMAGE" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_FUTSAL_FIELD_IMAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_FUTSAL_FIELD_IMAGE" ON "MATCH5_DBA"."COURT_IMAGE" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger COURT_IMAGE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."COURT_IMAGE_ID_TRIGGER" BEFORE
    INSERT ON court_image
    FOR EACH ROW
BEGIN
    SELECT
        court_image_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;
/
ALTER TRIGGER "MATCH5_DBA"."COURT_IMAGE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table COURT_IMAGE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_IMAGE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_IMAGE" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_IMAGE" ADD CONSTRAINT "PK_FUTSAL_FIELD_IMAGE" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_FUTSAL_FIELD_IMAGE"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."COURT_IMAGE" MODIFY ("COURT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COURT_IMAGE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_IMAGE" ADD CONSTRAINT "FK__FIELD_TO_FIELD_IMAGE" FOREIGN KEY ("COURT_ID")
	  REFERENCES "MATCH5_DBA"."COURT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table COURT_REVIEW
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."COURT_REVIEW" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"COURT_ID" NUMBER(*,0), 
	"CONTENT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"REVIEW_RATE" NUMBER(*,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."ID" IS '풋살장리뷰아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."COURT_ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."CONTENT" IS '리뷰내용';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."REVIEW_RATE" IS '평점';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_REVIEW"."CREATED_AT" IS '생성시각';
   COMMENT ON TABLE "MATCH5_DBA"."COURT_REVIEW"  IS '풋살장 리뷰';
  GRANT DELETE ON "MATCH5_DBA"."COURT_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."COURT_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."COURT_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."COURT_REVIEW" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_FUTSALFIELD_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_FUTSALFIELD_REVIEW" ON "MATCH5_DBA"."COURT_REVIEW" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger COURT_REVIEW_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."COURT_REVIEW_ID_TRIGGER" BEFORE
    INSERT ON court_review
    FOR EACH ROW
BEGIN
    SELECT
        court_review_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."COURT_REVIEW_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table COURT_REVIEW
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" MODIFY ("COURT_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" MODIFY ("REVIEW_RATE" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" ADD CONSTRAINT "PK_FUTSALFIELD_REVIEW" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_FUTSALFIELD_REVIEW"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" ADD CONSTRAINT "REVIEW_CHECK" CHECK (REVIEW_RATE >= 1 and REVIEW_RATE <= 5) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURT_REVIEW
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_REVIEW" ADD CONSTRAINT "FK_CLIENT_TO_FIELD_REVIEW" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table COURT_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."COURT_SCHEDULE" 
   (	"ID" NUMBER(*,0), 
	"COURT_ID" NUMBER(*,0), 
	"SCHEDULE_DATE" TIMESTAMP (6), 
	"START_T" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"END_T" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_PRICE" NUMBER(*,0), 
	"IS_RESERVED" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."ID" IS '구장스케줄아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."COURT_ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."SCHEDULE_DATE" IS '일자';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."START_T" IS '시작시간';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."END_T" IS '종료시간';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."PRODUCT_PRICE" IS '해당 시간대 가격';
   COMMENT ON COLUMN "MATCH5_DBA"."COURT_SCHEDULE"."IS_RESERVED" IS '예약여부 0=예약안됨,1=예약됨';
   COMMENT ON TABLE "MATCH5_DBA"."COURT_SCHEDULE"  IS '풋살장 스케줄';
  GRANT DELETE ON "MATCH5_DBA"."COURT_SCHEDULE" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."COURT_SCHEDULE" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."COURT_SCHEDULE" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."COURT_SCHEDULE" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_COURT_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_COURT_SCHEDULE" ON "MATCH5_DBA"."COURT_SCHEDULE" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger COURT_SCHEDULE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."COURT_SCHEDULE_ID_TRIGGER" BEFORE
    INSERT ON court_schedule
    FOR EACH ROW
BEGIN
    SELECT
        court_schedule_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;
/
ALTER TRIGGER "MATCH5_DBA"."COURT_SCHEDULE_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table COURT_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("COURT_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("SCHEDULE_DATE" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("START_T" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("END_T" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" ADD CONSTRAINT "PK_COURT_SCHEDULE" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_COURT_SCHEDULE"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" MODIFY ("PRODUCT_PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COURT_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."COURT_SCHEDULE" ADD CONSTRAINT "COURT_SCHEDULE_FK1" FOREIGN KEY ("COURT_ID")
	  REFERENCES "MATCH5_DBA"."COURT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table FUTSAL_LEVEL
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."FUTSAL_LEVEL" 
   (	"ID" NUMBER(*,0), 
	"LEVEL_NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"REQ_EXP" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."FUTSAL_LEVEL"."ID" IS '레벨아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."FUTSAL_LEVEL"."LEVEL_NAME" IS '레벨이름';
   COMMENT ON COLUMN "MATCH5_DBA"."FUTSAL_LEVEL"."REQ_EXP" IS '레벨업_필요경험치';
   COMMENT ON TABLE "MATCH5_DBA"."FUTSAL_LEVEL"  IS '실력등급';
  GRANT DELETE ON "MATCH5_DBA"."FUTSAL_LEVEL" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."FUTSAL_LEVEL" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."FUTSAL_LEVEL" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."FUTSAL_LEVEL" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_FUTSAL_LEVEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_FUTSAL_LEVEL" ON "MATCH5_DBA"."FUTSAL_LEVEL" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger FUTSAL_LEVEL_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."FUTSAL_LEVEL_ID_TRIGGER" BEFORE
    INSERT ON futsal_level
    FOR EACH ROW
BEGIN
    SELECT
        futsal_level_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."FUTSAL_LEVEL_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table FUTSAL_LEVEL
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."FUTSAL_LEVEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."FUTSAL_LEVEL" MODIFY ("LEVEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."FUTSAL_LEVEL" MODIFY ("REQ_EXP" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."FUTSAL_LEVEL" ADD CONSTRAINT "PK_FUTSAL_LEVEL" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_FUTSAL_LEVEL"  ENABLE;

--------------------------------------------------------
--  DDL for Table MATCHED_USERLIST
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."MATCHED_USERLIST" 
   (	"USER_ID" NUMBER(*,0), 
	"MATCHING_HISTORY_ID" NUMBER(*,0), 
	"TEAM" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."MATCHED_USERLIST"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHED_USERLIST"."MATCHING_HISTORY_ID" IS '매칭이력아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHED_USERLIST"."TEAM" IS '속한 팀(h vs a)';
   COMMENT ON TABLE "MATCH5_DBA"."MATCHED_USERLIST"  IS '매칭된 회원목록';
  GRANT DELETE ON "MATCH5_DBA"."MATCHED_USERLIST" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."MATCHED_USERLIST" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."MATCHED_USERLIST" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."MATCHED_USERLIST" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_MATCHED_USERLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_MATCHED_USERLIST" ON "MATCH5_DBA"."MATCHED_USERLIST" ("USER_ID", "MATCHING_HISTORY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MATCHED_USERLIST
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" MODIFY ("MATCHING_HISTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" MODIFY ("TEAM" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" ADD CONSTRAINT "PK_MATCHED_USERLIST" PRIMARY KEY ("USER_ID", "MATCHING_HISTORY_ID")
  USING INDEX "MATCH5_DBA"."PK_MATCHED_USERLIST"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" ADD CONSTRAINT "TEAM_CHECK" CHECK (team in ('H', 'A')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCHED_USERLIST
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" ADD CONSTRAINT "FK_CLIENT_TO_MATCHED_USERLIST" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHED_USERLIST" ADD CONSTRAINT "FK_MATCHING_TO_USERLIST" FOREIGN KEY ("MATCHING_HISTORY_ID")
	  REFERENCES "MATCH5_DBA"."MATCHING_HISTORY" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table MATCHING_ALARM
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."MATCHING_ALARM" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"CONTENT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" NUMBER(*,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MATCHING_HISTORY_ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."ID" IS '매칭알림아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."CONTENT" IS '내용';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."STATUS" IS '상태';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."CREATED_AT" IS '생성시각';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."MATCHING_HISTORY_ID" IS '비어있으면 매칭취소라는뜻';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_ALARM"."TYPE" IS '알림타입
';
   COMMENT ON TABLE "MATCH5_DBA"."MATCHING_ALARM"  IS '알림';
  GRANT DELETE ON "MATCH5_DBA"."MATCHING_ALARM" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."MATCHING_ALARM" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."MATCHING_ALARM" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."MATCHING_ALARM" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_MATCHING_ALARM
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_MATCHING_ALARM" ON "MATCH5_DBA"."MATCHING_ALARM" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger MATCHING_ALARM_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."MATCHING_ALARM_ID_TRIGGER" BEFORE
    INSERT ON matching_alarm
    FOR EACH ROW
BEGIN
    SELECT
        matching_alarm_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."MATCHING_ALARM_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table MATCHING_ALARM
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" ADD CONSTRAINT "PK_MATCHING_ALARM" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_MATCHING_ALARM"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" ADD CONSTRAINT "ALARM_STATUS_CHECK" CHECK (status in (0, 1)) ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MATCHING_ALARM
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" ADD CONSTRAINT "FK_CLIENT_TO_MATCHING_ALARM" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_ALARM" ADD CONSTRAINT "MATCHING_ALARM_FK1" FOREIGN KEY ("MATCHING_HISTORY_ID")
	  REFERENCES "MATCH5_DBA"."MATCHING_HISTORY" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table MATCHING_HISTORY
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."MATCHING_HISTORY" 
   (	"ID" NUMBER(*,0), 
	"COURT_ID" NUMBER(*,0), 
	"HTEAM_MANAGER_ID" NUMBER(*,0), 
	"ATEAM_MANAGER_ID" NUMBER(*,0), 
	"COURT_SCHEDULE_ID" NUMBER(*,0), 
	"STATUS" NUMBER(*,0) DEFAULT 0, 
	"CONFIRM_USER_COUNT" NUMBER(*,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."ID" IS '매칭이력아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."COURT_ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."HTEAM_MANAGER_ID" IS '홈팀 매니저 유저 아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."ATEAM_MANAGER_ID" IS '어웨이팀 매니저 유저 아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."COURT_SCHEDULE_ID" IS '풋살장 스케줄 아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."STATUS" IS '매칭상태';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."CONFIRM_USER_COUNT" IS '확정완료인원';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_HISTORY"."CREATED_AT" IS '생성시각';
   COMMENT ON TABLE "MATCH5_DBA"."MATCHING_HISTORY"  IS '매칭이력';
  GRANT DELETE ON "MATCH5_DBA"."MATCHING_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."MATCHING_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."MATCHING_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."MATCHING_HISTORY" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_MATCHING_HISTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_MATCHING_HISTORY" ON "MATCH5_DBA"."MATCHING_HISTORY" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger MATCHING_HISTORY_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."MATCHING_HISTORY_ID_TRIGGER" BEFORE
    INSERT ON matching_history
    FOR EACH ROW
BEGIN
    SELECT
        matching_history_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;

/
ALTER TRIGGER "MATCH5_DBA"."MATCHING_HISTORY_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table MATCHING_HISTORY
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" MODIFY ("COURT_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" MODIFY ("HTEAM_MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" MODIFY ("ATEAM_MANAGER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" MODIFY ("COURT_SCHEDULE_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "PK_MATCHING_HISTORY" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_MATCHING_HISTORY"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "MATCHING_STATUS_CHECK" CHECK (STATUS in (0, 1, 2, 3)) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCHING_HISTORY
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "MATCHING_HISTORY_FK1" FOREIGN KEY ("COURT_ID")
	  REFERENCES "MATCH5_DBA"."COURT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "FK_CLIENT_TO_MATCHING" FOREIGN KEY ("HTEAM_MANAGER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "FK_CLIENT_TO_MATCHING2" FOREIGN KEY ("ATEAM_MANAGER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_HISTORY" ADD CONSTRAINT "FK_SCHEDULE_TO_MATCHING" FOREIGN KEY ("COURT_SCHEDULE_ID")
	  REFERENCES "MATCH5_DBA"."COURT_SCHEDULE" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table MATCHING_QUEUE
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."MATCHING_QUEUE" 
   (	"USER_ID" NUMBER(*,0), 
	"SELECTED_DATE" TIMESTAMP (6), 
	"SELECTED_TIME" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_MANAGER" NUMBER(*,0), 
	"IS_OUTDOOR" NUMBER(*,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."SELECTED_DATE" IS '선택날짜';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."SELECTED_TIME" IS '선택시간';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."LOCATION" IS '선택지역';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."IS_MANAGER" IS '매니저여부';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."IS_OUTDOOR" IS '실내외여부';
   COMMENT ON COLUMN "MATCH5_DBA"."MATCHING_QUEUE"."CREATED_AT" IS '생성시각';
   COMMENT ON TABLE "MATCH5_DBA"."MATCHING_QUEUE"  IS '매칭대기';
  GRANT DELETE ON "MATCH5_DBA"."MATCHING_QUEUE" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."MATCHING_QUEUE" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."MATCHING_QUEUE" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."MATCHING_QUEUE" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_MATCHING_QUEUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_MATCHING_QUEUE" ON "MATCH5_DBA"."MATCHING_QUEUE" ("USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table MATCHING_QUEUE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("SELECTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("SELECTED_TIME" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("IS_MANAGER" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("IS_OUTDOOR" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" ADD CONSTRAINT "PK_MATCHING_QUEUE" PRIMARY KEY ("USER_ID")
  USING INDEX "MATCH5_DBA"."PK_MATCHING_QUEUE"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" ADD CONSTRAINT "MANAGER_CHECK" CHECK (IS_MANAGER in (0, 1)) ENABLE;
  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" ADD CONSTRAINT "OUTDOOR_CHECK" CHECK (IS_OUTDOOR in (0, 1,2)) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCHING_QUEUE
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."MATCHING_QUEUE" ADD CONSTRAINT "FK_CLIENT_TO_MATCHING_QUEUE" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table PAYMENT_HISTORY
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."PAYMENT_HISTORY" 
   (	"USER_ID" NUMBER(*,0), 
	"MATCHING_HISTORY_ID" NUMBER(*,0), 
	"STATUS" NUMBER(*,0) DEFAULT 1
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."PAYMENT_HISTORY"."USER_ID" IS '유저아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."PAYMENT_HISTORY"."MATCHING_HISTORY_ID" IS '매칭이력아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."PAYMENT_HISTORY"."STATUS" IS '결제여부 1=완료,2=환불';
   COMMENT ON TABLE "MATCH5_DBA"."PAYMENT_HISTORY"  IS '결제이력';
  GRANT DELETE ON "MATCH5_DBA"."PAYMENT_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."PAYMENT_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."PAYMENT_HISTORY" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."PAYMENT_HISTORY" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_PAYMENT_HISTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_PAYMENT_HISTORY" ON "MATCH5_DBA"."PAYMENT_HISTORY" ("USER_ID", "MATCHING_HISTORY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PAYMENT_HISTORY
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" MODIFY ("MATCHING_HISTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" ADD CONSTRAINT "PK_PAYMENT_HISTORY" PRIMARY KEY ("USER_ID", "MATCHING_HISTORY_ID")
  USING INDEX "MATCH5_DBA"."PK_PAYMENT_HISTORY"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" ADD CONSTRAINT "PAYMENT_STATUS_CHECK" CHECK (status in (0, 1, 2)) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_HISTORY
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" ADD CONSTRAINT "FK_CLIENT_TO_PAYMENT" FOREIGN KEY ("USER_ID")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."PAYMENT_HISTORY" ADD CONSTRAINT "FK_MATCHING_TO_PAYMENT" FOREIGN KEY ("MATCHING_HISTORY_ID")
	  REFERENCES "MATCH5_DBA"."MATCHING_HISTORY" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Table STADIUM
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."STADIUM" 
   (	"ID" NUMBER(*,0), 
	"LOCATION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_PARKING" NUMBER(*,0) DEFAULT 0, 
	"IS_TOILET" NUMBER(*,0) DEFAULT 0, 
	"IS_SHOWER" NUMBER(*,0) DEFAULT 0, 
	"IS_SHOES" NUMBER(*,0) DEFAULT 0, 
	"RENTAL_INTRO" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAT" NUMBER(*,10), 
	"LNG" NUMBER(*,10)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."ID" IS '풋살장아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."LOCATION" IS '지역(구)';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."IS_PARKING" IS '주차여부';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."IS_TOILET" IS '화장실유무';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."IS_SHOWER" IS '샤워실유무';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."IS_SHOES" IS '풋살화 대여유무';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."RENTAL_INTRO" IS '주의사항';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."NAME" IS '풋살장이름';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."LAT" IS '위도';
   COMMENT ON COLUMN "MATCH5_DBA"."STADIUM"."LNG" IS '경도';
   COMMENT ON TABLE "MATCH5_DBA"."STADIUM"  IS '풋살장';
  GRANT DELETE ON "MATCH5_DBA"."STADIUM" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."STADIUM" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."STADIUM" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."STADIUM" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_FUTSAL_FIELD
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_FUTSAL_FIELD" ON "MATCH5_DBA"."STADIUM" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger STADIUM_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MATCH5_DBA"."STADIUM_ID_TRIGGER" BEFORE
    INSERT ON stadium
    FOR EACH ROW
BEGIN
    SELECT
        stadium_seq.NEXTVAL
    INTO :new.id
    FROM
        dual;

END;
/
ALTER TRIGGER "MATCH5_DBA"."STADIUM_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table STADIUM
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."STADIUM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."STADIUM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."STADIUM" MODIFY ("LAT" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."STADIUM" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."STADIUM" ADD CONSTRAINT "PK_FUTSAL_FIELD" PRIMARY KEY ("ID")
  USING INDEX "MATCH5_DBA"."PK_FUTSAL_FIELD"  ENABLE;
  ALTER TABLE "MATCH5_DBA"."STADIUM" ADD CONSTRAINT "PARKING_CHECK" CHECK (IS_PARKING in (0, 1)) ENABLE;
  ALTER TABLE "MATCH5_DBA"."STADIUM" ADD CONSTRAINT "RESTROOM_CHECK" CHECK ("IS_TOILET"=0 OR "IS_TOILET"=1) ENABLE;
  ALTER TABLE "MATCH5_DBA"."STADIUM" ADD CONSTRAINT "SHOWER_CHECK" CHECK (IS_SHOWER in (0, 1)) ENABLE;
  ALTER TABLE "MATCH5_DBA"."STADIUM" ADD CONSTRAINT "SHOES_RENTAL_CHECK" CHECK ("IS_SHOES"=0 OR "IS_SHOES"=1) ENABLE;
  ALTER TABLE "MATCH5_DBA"."STADIUM" MODIFY ("LNG" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table USER_REVIEW
--------------------------------------------------------

  CREATE TABLE "MATCH5_DBA"."USER_REVIEW" 
   (	"FROM_USER" NUMBER(*,0), 
	"TO_USER" NUMBER(*,0), 
	"MATCHING_HISTORY_ID" NUMBER(*,0), 
	"REVIEW_RATE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "MATCH5_DBA"."USER_REVIEW"."FROM_USER" IS '평가자 아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."USER_REVIEW"."TO_USER" IS '피평가자 아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."USER_REVIEW"."MATCHING_HISTORY_ID" IS '매칭이력아이디';
   COMMENT ON COLUMN "MATCH5_DBA"."USER_REVIEW"."REVIEW_RATE" IS '평점';
   COMMENT ON TABLE "MATCH5_DBA"."USER_REVIEW"  IS '회원평가';
  GRANT DELETE ON "MATCH5_DBA"."USER_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT INSERT ON "MATCH5_DBA"."USER_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT SELECT ON "MATCH5_DBA"."USER_REVIEW" TO "MATCH5_TEAM_ROLE";
  GRANT UPDATE ON "MATCH5_DBA"."USER_REVIEW" TO "MATCH5_TEAM_ROLE";
--------------------------------------------------------
--  DDL for Index PK_USER_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_USER_REVIEW" ON "MATCH5_DBA"."USER_REVIEW" ("FROM_USER", "TO_USER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER_REVIEW1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATCH5_DBA"."PK_USER_REVIEW1" ON "MATCH5_DBA"."USER_REVIEW" ("FROM_USER", "TO_USER", "MATCHING_HISTORY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table USER_REVIEW
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" ADD CONSTRAINT "PK_USER_REVIEW" PRIMARY KEY ("FROM_USER", "TO_USER", "MATCHING_HISTORY_ID")
  USING INDEX (CREATE UNIQUE INDEX "MATCH5_DBA"."PK_USER_REVIEW1" ON "MATCH5_DBA"."USER_REVIEW" ("FROM_USER", "TO_USER", "MATCHING_HISTORY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" )  ENABLE;
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" MODIFY ("FROM_USER" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" MODIFY ("TO_USER" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" MODIFY ("MATCHING_HISTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" MODIFY ("REVIEW_RATE" NOT NULL ENABLE);
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" ADD CONSTRAINT "REVIEW_RAGE_CHECK" CHECK (REVIEW_RATE in (-1, 1, 2)) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_REVIEW
--------------------------------------------------------

  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" ADD CONSTRAINT "FK_CLIENT_TO_USER_REVIEW" FOREIGN KEY ("FROM_USER")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" ADD CONSTRAINT "FK_CLIENT_TO_USER_REVIEW2" FOREIGN KEY ("TO_USER")
	  REFERENCES "MATCH5_DBA"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "MATCH5_DBA"."USER_REVIEW" ADD CONSTRAINT "FK_MATCHING_TO_USER_REVIEW" FOREIGN KEY ("MATCHING_HISTORY_ID")
	  REFERENCES "MATCH5_DBA"."MATCHING_HISTORY" ("ID") ENABLE;

--------------------------------------------------------
--  DDL for Procedure DELETE_COURT_REVIEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MATCH5_DBA"."DELETE_COURT_REVIEW" (
    v_court_review_id in COURT.id%Type,
    success_row out int
)
    IS
    new_avg_review_rate court.AVG_RATE%TYPE;
    v_court_id          court.id%type;
BEGIN
    --구장 아이디 가져오기
    select court_id
    into v_court_id
    from COURT_REVIEW
    where id = v_court_review_id;

    -- 구장 평가 삭제
    delete from COURT_REVIEW
    where id=v_court_review_id;


    -- 해당 구장의 평균 평가 점수를 계산합니다.
    SELECT round(AVG(REVIEW_RATE), 1)
    INTO new_avg_review_rate
    FROM COURT_REVIEW
    WHERE court_id = v_court_id;


    -- 해당 구장 테이블의 평균 평가 점수를 업데이트합니다.
    UPDATE court
    SET AVG_RATE = new_avg_review_rate
    WHERE id = v_court_id;

    -- 성공 상태 반환
    success_row := 1;
EXCEPTION
    WHEN OTHERS THEN
        -- 실패 상태 반환
        success_row := 0;
END;

/


--------------------------------------------------------
--  DDL for Procedure RESERVE_COURT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MATCH5_DBA"."RESERVE_COURT" (
    v_location IN STADIUM.location%type,
    v_selected_date IN MATCHING_QUEUE.SELECTED_DATE%type, -- 테이블상 timestamp 안되면 varchar로 수정하기
    v_selected_time IN MATCHING_QUEUE.SELECTED_TIME%type, -- 테이블상 varchar
    v_home_manager_id IN NUMBER,
    v_away_manager_id IN NUMBER,
    success_row OUT NUMBER,
    matching_history_id out number
)
    IS
    v_court_schedule_id STADIUM.id%type;
    v_court_id          STADIUM.id%type;

BEGIN
    --가능한 구장 스케줄 아이디,구장 아이디를 반환한다.
    --오라클에서는 INTO 절을 사용하여 변수에 값을 할당할 때 중첩된 쿼리 내부에서 사용할 수 없습니다.
    --중첩된 쿼리 내부에서는 결과를 반환하는 SELECT 문이 바로 사용되기 때문에 INTO 절을 사용할 수 없습니다.
    SELECT schedule_id, court_id
    INTO v_court_schedule_id,v_court_id
    FROM (SELECT cs.id as schedule_id, c.id as court_id
          FROM (SELECT s.id AS stadium_id, AVG(c.AVG_RATE) AS stadium_avg_review_rate
                FROM STADIUM s
                         JOIN MATCH5_DBA.COURT c ON s.ID = c.STADIUM_ID
                WHERE s.LOCATION = v_location
                GROUP BY s.id
                ORDER BY stadium_avg_review_rate DESC) ts
                   JOIN MATCH5_DBA.COURT c ON ts.stadium_id = c.STADIUM_ID
                   JOIN MATCH5_DBA.COURT_SCHEDULE cs ON c.ID = cs.COURT_ID
          WHERE cs.SCHEDULE_DATE = v_selected_date
            AND cs.START_T = v_selected_time
            AND cs.IS_RESERVED = 0
          ORDER BY ts.stadium_avg_review_rate DESC, c.AVG_RATE DESC) result
    WHERE ROWNUM = 1;

--     해당 스케줄은 예약처리
    update COURT_SCHEDULE set IS_RESERVED=1 where id = v_court_schedule_id;

--     매칭 히스토리 생성 및 생성된 매칭 히스토리 아이디 반환
    insert into MATCHING_HISTORY(court_id, hteam_manager_id, ateam_manager_id, court_schedule_id)
    values (v_court_id, v_home_manager_id, v_away_manager_id, v_court_schedule_id);

-- 생성된 매칭 히스토리의 ID 값을 반환
    SELECT id INTO matching_history_id FROM MATCHING_HISTORY WHERE rownum = 1 ORDER BY id DESC;

     DBMS_OUTPUT.PUT_LINE(v_court_id);
     DBMS_OUTPUT.PUT_LINE(v_home_manager_id);
     DBMS_OUTPUT.PUT_LINE(v_away_manager_id);
     DBMS_OUTPUT.PUT_LINE(v_court_schedule_id);
    
    
    -- 성공 상태 반환
    success_row := 1;

EXCEPTION
    WHEN OTHERS THEN
        -- 실패 상태 반환
        success_row := 0;
END;

/


--------------------------------------------------------
--  DDL for Procedure SAVE_COURT_REVIEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MATCH5_DBA"."SAVE_COURT_REVIEW" (
    v_user_id in CLIENT.id%TYPE,
    v_court_id in COURT.id%Type,
    v_content in COURT_REVIEW.content%TYPE,
    v_review_rate in COURT_REVIEW.review_rate%type,
    success_row out int
)
    IS
    new_avg_review_rate court.AVG_RATE%TYPE;
BEGIN

    -- 구장평가 생성
    insert into COURT_REVIEW(user_id, court_id, content, review_rate)
    values (v_user_id,v_court_id,v_content,v_review_rate);


    -- 해당 구장의 평균 평가 점수를 계산합니다.
    SELECT round(AVG(REVIEW_RATE),1)
    INTO new_avg_review_rate
    FROM COURT_REVIEW
    WHERE court_id = v_court_id;


    -- 해당 구장 테이블의 평균 평가 점수를 업데이트합니다.
    UPDATE court
    SET AVG_RATE = new_avg_review_rate
    WHERE id = v_court_id;

    -- 성공 상태 반환
    success_row := 1;
EXCEPTION
    WHEN OTHERS THEN
        -- 실패 상태 반환
        success_row := 0;
END;

/

--------------------------------------------------------
--  DDL for Procedure UPDATE_CLIENT_EXP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MATCH5_DBA"."UPDATE_CLIENT_EXP" (
    client_id IN client.id%TYPE,
    exp_change IN NUMBER
)
    IS
    new_exp NUMBER;
    new_level_id NUMBER;
BEGIN
    -- 현재 경험치 업데이트
    SELECT current_exp + exp_change INTO new_exp
    FROM client
    WHERE id = client_id;

    -- 새로운 레벨 ID 계산
    IF new_exp BETWEEN 0 AND 200 THEN
        new_level_id := 1;
    ELSIF new_exp BETWEEN 201 AND 400 THEN
        new_level_id := 2;
    ELSIF new_exp BETWEEN 401 AND 600 THEN
        new_level_id := 3;
    ELSIF new_exp BETWEEN 601 AND 800 THEN
        new_level_id := 4;
    ELSE
        new_level_id := 5;
    END IF;

    -- 레벨 업데이트
    UPDATE client
    SET current_exp = new_exp,
        level_id = new_level_id
    WHERE id = client_id;
END;

/


--------------------------------------------------------
--  DDL for Procedure UPDATE_COURT_REVIEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MATCH5_DBA"."UPDATE_COURT_REVIEW" (
    v_court_review_id in COURT.id%Type,
    v_content in COURT_REVIEW.content%TYPE,
    v_review_rate in COURT_REVIEW.review_rate%type,
    success_row out int
)
    IS
    new_avg_review_rate court.AVG_RATE%TYPE;
    v_court_id          court.id%type;
BEGIN
    --구장 아이디 가져오기
    select court_id
    into v_court_id
    from COURT_REVIEW
    where id = v_court_review_id;

    -- 구장 평가 수정
    update COURT_REVIEW
    set content     = v_content,
        REVIEW_RATE = v_review_rate
    where id = v_court_review_id;


    -- 해당 구장의 평균 평가 점수를 계산합니다.
    SELECT round(AVG(REVIEW_RATE), 1)
    INTO new_avg_review_rate
    FROM COURT_REVIEW
    WHERE court_id = v_court_id;


    -- 해당 구장 테이블의 평균 평가 점수를 업데이트합니다.
    UPDATE court
    SET AVG_RATE = new_avg_review_rate
    WHERE id = v_court_id;

    -- 성공 상태 반환
    success_row := 1;
EXCEPTION
    WHEN OTHERS THEN
        -- 실패 상태 반환
        success_row := 0;
END;

/

--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."CLIENT_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Sequence COURT_IMAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."COURT_IMAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COURT_IMAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."COURT_IMAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COURT_REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."COURT_REVIEW_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 220 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COURT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."COURT_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 240 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COURT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."COURT_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 240 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FUTSAL_LEVEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."FUTSAL_LEVEL_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MATCHING_ALARM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."MATCHING_ALARM_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10428 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MATCHING_HISTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."MATCHING_HISTORY_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1102 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STADIUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MATCH5_DBA"."STADIUM_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 60 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
